In [2]:
import numpy as np 
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with dates

In [8]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [10]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
597 2018-10-18        4846        1       1       2018
334 2019-10-27        1130       14      48       2019
134 2019-11-17        6049       16       1       2019
714 2019-08-07        4659        1       1       2019
462 2018-09-14         626       13       1       2018

## 2. Extract month

In [11]:
date['date_month'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
208 2019-06-24        3919        2      22       2019           6
456 2018-12-04        1622        9       4       2018          12
86  2019-06-27        3904        1      29       2019           6
7   2019-03-27        5022        2      41       2019           3
205 2019-12-05        5722       25     260       2019          12

In [12]:
date['month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  date_month month_name
0 2019-12-10        5628       25       3       2019          12   December
1 2018-08-15        3646       14     157       2018           8     August
2 2018-10-23        1859       25       1       2018          10    October
3 2019-08-17        7292       25       1       2019           8     August
4 2019-01-06        4344       25       3       2019           1    January

## Extract days

In [13]:
date['date_day'] = date['date'].dt.day
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [14]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()

# exact week of the year
date['date_week'] = date['date'].dt.isocalendar().week

# exact quater 
date['date_quater'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_day,date_dow,date_dow_name,date_week,date_quater
0,2019-12-10,2019,12,December,10,1,Tuesday,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [15]:
# is weekend

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_day,date_dow,date_dow_name,date_week,date_quater,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,50,4,0
1,2018-08-15,2018,8,August,15,2,Wednesday,33,3,0
2,2018-10-23,2018,10,October,23,1,Tuesday,43,4,0
3,2019-08-17,2019,8,August,17,5,Saturday,33,3,1
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## Extract Time elapsed btw dates

In [16]:
import datetime 
today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 9, 13, 35, 56, 44768)

In [17]:
today - date['date']

0     2403 days 13:35:56.044768
1     2885 days 13:35:56.044768
2     2816 days 13:35:56.044768
3     2518 days 13:35:56.044768
4     2741 days 13:35:56.044768
                 ...
995   2831 days 13:35:56.044768
996   2772 days 13:35:56.044768
997   2620 days 13:35:56.044768
998   2685 days 13:35:56.044768
999   2459 days 13:35:56.044768
Name: date, Length: 1000, dtype: timedelta64[ns]

In [18]:
(today - date['date']).dt.days

0      2403
1      2885
2      2816
3      2518
4      2741
       ...
995    2831
996    2772
997    2620
998    2685
999    2459
Name: date, Length: 1000, dtype: int64

In [23]:
# Months passed

np.round((today - date['date']) / np.timedelta64(30, 'D'),0)

0      80.0
1      96.0
2      94.0
3      84.0
4      91.0
       ...
995    94.0
996    92.0
997    87.0
998    90.0
999    82.0
Name: date, Length: 1000, dtype: float64

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [25]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [26]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [27]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Ectract Time part

In [28]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [29]:
today - time['date']

0     4589 days 12:45:56.044768
1     4453 days 13:55:56.044768
2     4939 days 13:14:56.044768
3     4241 days 13:04:56.044768
4     4638 days 14:24:56.044768
                 ...
995   5228 days 12:45:56.044768
996   4549 days 14:21:56.044768
997   5014 days 13:58:56.044768
998   5130 days 14:01:56.044768
999   4402 days 14:10:56.044768
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# in seconds
(today - time['date']) / np.timedelta64(1,'s')

0      3.965356e+08
1      3.847894e+08
2      4.267773e+08
3      3.664695e+08
4      4.007751e+08
           ...
995    4.517452e+08
996    3.930853e+08
997    4.332599e+08
998    4.432825e+08
999    3.803839e+08
Name: date, Length: 1000, dtype: float64

In [31]:
# in minutes

(today - time['date']) / np.timedelta64(1,'h')

0      110148.765568
1      106885.932235
2      118549.248901
3      101797.082235
4      111326.415568
           ...
995    125484.765568
996    109190.365568
997    120349.982235
998    123134.032235
999    105662.182235
Name: date, Length: 1000, dtype: float64