In [22]:
import numpy as np 
import pandas as pd

In [23]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [24]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [25]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [26]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with dates

In [28]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [29]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [30]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
403 2018-12-03         639       27       1       2018
741 2019-11-10        7318       25       1       2019
290 2018-12-05        4254       16      37       2018
126 2019-07-20        1944       11      16       2019
321 2019-12-04        2981       26     461       2019

## 2. Extract month

In [31]:
date['date_month'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
275 2019-01-12        4850       26       3       2019           1
199 2019-01-27        3817       28       4       2019           1
898 2019-02-20        2945       22       2       2019           2
337 2019-07-15        4180       16       1       2019           7
26  2019-01-09        6825       16       4       2019           1

In [32]:
date['month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  date_month month_name
0 2019-12-10        5628       25       3       2019          12   December
1 2018-08-15        3646       14     157       2018           8     August
2 2018-10-23        1859       25       1       2018          10    October
3 2019-08-17        7292       25       1       2019           8     August
4 2019-01-06        4344       25       3       2019           1    January

## Extract days

In [33]:
date['date_day'] = date['date'].dt.day
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [34]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()

# exact week of the year
date['date_week'] = date['date'].dt.isocalendar().week

# exact quater 
date['date_quater'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_day,date_dow,date_dow_name,date_week,date_quater
0,2019-12-10,2019,12,December,10,1,Tuesday,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [35]:
# is weekend

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_day,date_dow,date_dow_name,date_week,date_quater,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,50,4,0
1,2018-08-15,2018,8,August,15,2,Wednesday,33,3,0
2,2018-10-23,2018,10,October,23,1,Tuesday,43,4,0
3,2019-08-17,2019,8,August,17,5,Saturday,33,3,1
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## Extract Time elapsed btw dates

In [37]:
import datetime 
today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 8, 20, 14, 3, 876984)

In [38]:
today - date['date']

0     2402 days 20:14:03.876984
1     2884 days 20:14:03.876984
2     2815 days 20:14:03.876984
3     2517 days 20:14:03.876984
4     2740 days 20:14:03.876984
                 ...
995   2830 days 20:14:03.876984
996   2771 days 20:14:03.876984
997   2619 days 20:14:03.876984
998   2684 days 20:14:03.876984
999   2458 days 20:14:03.876984
Name: date, Length: 1000, dtype: timedelta64[ns]

In [39]:
(today - date['date']).dt.days

0      2402
1      2884
2      2815
3      2517
4      2740
       ...
995    2830
996    2771
997    2619
998    2684
999    2458
Name: date, Length: 1000, dtype: int64

In [ ]:
# Months passed

no.round((today - date['date']) / np.timedelta64(1, 'M'),0)